######### é”šç‚¹ start #######
# ç­–ç•¥ç»„ç›¸å…³
pr: &pr {type: select, proxies: [é»˜è®¤, é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, å…¶å®ƒåœ°åŒº, å…¨éƒ¨èŠ‚ç‚¹, è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
#è¿™é‡Œæ˜¯è®¢é˜…æ›´æ–°å’Œå»¶è¿Ÿæµ‹è¯•ç›¸å…³çš„
p: &p {type: http, interval: 3600, health-check: {enable: true, url: "https://www.gstatic.com/generate_204", interval: 300}}
######### é”šç‚¹ end #######

# url é‡Œå¡«å†™è‡ªå·±çš„è®¢é˜…,åç§°ä¸èƒ½é‡å¤
proxy-providers:
  ByWave:
    !!merge <<: *p
    url: "{{replace (command_output 'rbw get bywave_subscription_url') '\n' ''}}"
  BoostNet:
    !!merge <<: *p
    url: "{{replace (command_output 'rbw get boostnet2_subscription_url') '\n' ''}}"
ipv6: true
allow-lan: true
mixed-port: 7890
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
global-client-fingerprint: chrome
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - Mijia Cloud
tun:
  enable: true
  # stack: mixed
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - +.lan
    - +.local
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    rule-set:cn_domain,private:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    rule-set:geolocation-!cn:
      - https://dns.cloudflare.com/dns-query#dns
      - https://dns.google/dns-query#dns
proxies:
  - name: ç›´è¿
    type: direct
    udp: true
proxy-groups:
  - {name: é»˜è®¤, type: select, proxies: [è‡ªåŠ¨é€‰æ‹©, ç›´è¿, é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, å…¶å®ƒåœ°åŒº, å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: dns, type: select, proxies: [è‡ªåŠ¨é€‰æ‹©, é»˜è®¤, é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, å…¶å®ƒåœ°åŒº, å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: Google, !!merge <<: *pr}
  - {name: Github, !!merge <<: *pr}
  - {name: OpenAI, !!merge <<: *pr}
  - {name: Gemini, !!merge <<: *pr}
  - {name: Telegram, !!merge <<: *pr}
  - {name: Twitter, !!merge <<: *pr}
  - {name: Pixiv, !!merge <<: *pr}
  - {name: å“”å“©å“”å“©, !!merge <<: *pr}
  - {name: å“”å“©ä¸œå—äºš, !!merge <<: *pr}
  - {name: å·´å“ˆå§†ç‰¹, !!merge <<: *pr}
  - {name: YouTube, !!merge <<: *pr}
  - {name: NETFLIX, !!merge <<: *pr}
  - {name: Spotify, !!merge <<: *pr}
  - {name: å›½å†…, type: select, proxies: [ç›´è¿, é»˜è®¤, é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, å…¶å®ƒåœ°åŒº, å…¨éƒ¨èŠ‚ç‚¹, è‡ªåŠ¨é€‰æ‹©]}
  - {name: å…¶ä»–, !!merge <<: *pr}
  #åˆ†éš”,ä¸‹é¢æ˜¯åœ°åŒºåˆ†ç»„
  - {name: é¦™æ¸¯, type: select, include-all-providers: true, filter: "(?i)æ¸¯|hk|hongkong|hong kong"}
  - {name: å°æ¹¾, type: select, include-all-providers: true, filter: "(?i)å°|tw|taiwan"}
  - {name: æ—¥æœ¬, type: select, include-all-providers: true, filter: "(?i)æ—¥|jp|japan"}
  - {name: ç¾å›½, type: select, include-all-providers: true, filter: "(?i)ç¾|us|unitedstates|united states"}
  - {name: æ–°åŠ å¡, type: select, include-all-providers: true, filter: "(?i)(æ–°|sg|singapore)"}
  - {name: å…¶å®ƒåœ°åŒº, type: select, include-all-providers: true, filter: "(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¯ğŸ‡µ|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¨ğŸ‡³|æ¸¯|hk|hongkong|å°|tw|taiwan|æ—¥|jp|japan|æ–°|sg|singapore|ç¾|us|unitedstates)).*"}
  - {name: å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all-providers: true}
  - {name: è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all-providers: true, tolerance: 10}
rules:
  - GEOIP,lan,ç›´è¿,no-resolve
  # {{#each mihomo_direct_suffixes}}
  - DOMAIN-SUFFIX,{{this}},ç›´è¿,no-resolve
  # {{/each}}
  - RULE-SET,biliintl_domain,å“”å“©ä¸œå—äºš
  - RULE-SET,github_domain,Github
  - RULE-SET,twitter_domain,Twitter
  - RULE-SET,openai_domain,OpenAI
  - RULE-SET,gemini_domain,Gemini
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,google_domain,Google
  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,netflix_domain,NETFLIX
  - RULE-SET,bilibili_domain,å“”å“©å“”å“©
  - RULE-SET,bahamut_domain,å·´å“ˆå§†ç‰¹
  - RULE-SET,spotify_domain,Spotify
  - RULE-SET,pixiv_domain,Pixiv
  - RULE-SET,cn_domain,å›½å†…
  - DOMAIN-SUFFIX,pandora.com,ç¾å›½
  - RULE-SET,geolocation-!cn,å…¶ä»–
  - RULE-SET,google_ip,Google
  - RULE-SET,netflix_ip,NETFLIX
  - RULE-SET,telegram_ip,Telegram
  - RULE-SET,twitter_ip,Twitter
  - RULE-SET,cn_ip,å›½å†…
  - MATCH,å…¶ä»–
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: yaml}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: yaml}
rule-providers:
  private:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml
  cn_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml
  biliintl_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/biliintl.yaml
  github_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.yaml
  twitter_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.yaml
  openai_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/openai.yaml
  gemini_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/google-gemini.yaml
  youtube_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.yaml
  google_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.yaml
  telegram_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.yaml
  netflix_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.yaml
  bilibili_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.yaml
  bahamut_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bahamut.yaml
  spotify_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.yaml
  pixiv_domain:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/pixiv.yaml
  geolocation-!cn:
    !!merge <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml
  cn_ip:
    !!merge <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml
  google_ip:
    !!merge <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.yaml
  netflix_ip:
    !!merge <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.yaml
  twitter_ip:
    !!merge <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.yaml
  telegram_ip:
    !!merge <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.yaml
